apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-store
  namespace: kubeflow-user-example-com
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 32Gi
